### ISSUE TITLE
installation command error : Command errored out with exit status 1:

### ISSUE THREAD

**Issue by Xephobia** [b1naryth1ef/disco#156]

**Comment by LMByrne** [comment]
It'd be helpful to have some actual information like how are you installing it (are you installing the pip package or you pip installing from straight from the repo), the full error and what OS this happened on.

But before you give me that, if you're doing "pip install disco-py", you may want to try "pip install git+https://github.com/b1naryth1ef/disco".

**Comment by Xephobia** [comment]
i use Pycharm, i dont use terminal, i install with the library list

**Comment by LMByrne** [comment]
Sorry for the late response, but I'd still recommend trying to install it directly from the repo using either the link i sent in my previous message or more likely just `https://github.com/b1naryth1ef/disco` (I'm not too familiar with pycharm myself but I believe there are instruction on how to install from custom repository [here](https://www.jetbrains.com/help/pycharm/installing-uninstalling-and-upgrading-packages.html`) in-case you didn't know how.

**Comment by pehala** [comment]
I had the same problem with python 3.7, it failed because of gevent, so I think gevent version that disco uses is not compatible with that.

**Comment by b1naryth1ef** [comment]
Opening an issue without any content will not result in you getting any help for your problem, and is generally pretty rude (since I have to respond now asking for more information). When filing issues on open source projects you should always provide as much information as possible (for example, full console output, command being ran, OS information, etc). Closing until you can provide more context for information.
